# Generated by Django 5.1.6 on 2025-02-18 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='users.role', verbose_name='Роли'),
        ),
    ]
