# Generated by Django 5.1.6 on 2025-02-21 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswers',
            name='user_return',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserReturn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCreator', to=settings.AUTH_USER_MODEL),
        ),
    ]
