# Generated by Django 5.1.6 on 2025-02-24 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_questionanswers_user_return_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswers',
            old_name='content',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question',
        ),
        migrations.AddField(
            model_name='questions',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='survey.survey'),
        ),
        migrations.AddField(
            model_name='survey',
            name='user_receiver',
            field=models.ManyToManyField(related_name='UserReceiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionanswers',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='question', to='survey.questions'),
        ),
        migrations.AlterField(
            model_name='questionanswers',
            name='user_return',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
