# Generated by Django 5.1.6 on 2025-02-24 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_questions_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='survey.survey'),
        ),
    ]
