# Generated by Django 5.1.6 on 2025-02-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_questions_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
