# Generated by Django 5.1.6 on 2025-03-01 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_alter_questionanswers_user_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswers',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='survey.questions'),
        ),
    ]
